#!/usr/bin/env bash
# =============================================================================
# workflow/03_build_portable_analysis_bundle.sh  —  PIPELINE STEPS 3-7 of 7
#
# This file performs 5 of the pipeline's 7 total steps (its own internal
# "# Step N" comment banners below continue the SAME numbering used by
# CreateStrategusAnalysisSpecification.R [step 1] and StrategusCodeToRun.R
# [step 2] — there is exactly one step-numbering scheme for this whole repo):
#   Step 3 — sync study content into the bundle
#   Step 4 — sync the JDBC driver into the bundle
#   Step 5 — generate the bundle's README.md + .env
#   Step 6 — commit and push the bundle to GitLab
#   Step 7 — build the connection-agnostic zip fallback
# Console output is tagged [Step N] per section so log lines are traceable to
# exactly one step. Run this after CreateStrategusAnalysisSpecification.R
# (step 1) and a passing StrategusCodeToRun.R devcontainer run (step 2).
#
# NOTE ON THE FILENAME: this workspace's OTHER study repos (and the
# synthea-omop-template scaffold) all number their deployment-bundle script
# "09", regardless of that repo's own step count — a cross-repo convention so
# "09" always means "build the bundle" when working across many repos. This
# repo's file was deliberately renumbered to "03" instead, to give
# pad-amp-ed-desc its own fully self-consistent, gapless 1-7 step sequence
# (a repo-local decision, not a workspace-wide policy change — do not assume
# other repos follow this).
#
# PURPOSE
# -------
# Packages the pad-amp-ed-desc HYBRID Strategus analysis (ED utilization after
# major lower extremity amputation) into a self-contained bundle for execution
# on Duke PRCC, then pushes it to a GitLab remote so PRCC can clone/pull it.
#
# HYBRID bundle: unlike the pure-Strategus pad-oler-aki-desc bundle, this study
# runs Strategus::execute() AND a retained custom analysis + Word-manuscript
# report. So step 3 syncs BOTH the self-contained inst/ directory (Strategus
# cohort JSON/SQL/Cohorts.csv + the generated analysis-spec JSON) plus
# CreateStrategusAnalysisSpecification.R (the aki-desc pattern), AND the report
# chain + retained custom step + covariate CSVs (the amp-ed additions):
#   R/report_extended.R -> R/report.R, R/report_helpers.R,
#   R/report_descriptive.R, scripts/analysis/descriptive_ed_analysis.R,
#   covariates/*.csv.
#
# The Duke PRCC runtime layer (R/connection.R, R/drivers.R, config.R,
# run_analysis.R, setup_prcc_env.sh, install_packages.R, install_r_packages.sh,
# run_analysis.sh, export_results_for_review.R, vendor_packages/, drivers/) is
# committed into portable/pad_amp_ed_desc/ once and is NOT regenerated by this
# script — step 3 only syncs the study-content files above; step 5 regenerates
# .env / README.md.
#
# A dated zip (step 7) is also written to dist/ as a connection-agnostic local
# fallback.
#
# PREREQUISITES
# -------------
# In this repo's own .env (gitignored) OR the workspace .env one level up:
#   BUNDLE_GITLAB_REMOTE   Full SSH URL of the target GitLab repo (you create it).
#   BUNDLE_GIT_USER_NAME   Name for git commits inside the bundle repo.
#   BUNDLE_GIT_USER_EMAIL  Duke email for git commits.
# And in the workspace .env (INST_OMOP_* — shared site connection details):
#   INST_OMOP_SERVER, INST_OMOP_DATABASE, INST_OMOP_SPN_HOST,
#   INST_OMOP_VOCAB_SCHEMA, INST_OMOP_CDM_SCHEMA, INST_OMOP_RESULTS_SCHEMA,
#   INST_OMOP_CDM_DATABASE_ID, INST_OMOP_CDM_DATABASE_NAME,
#   INST_OMOP_CDM_DATABASE_DESCRIPTION
#
# SSH auth: the dev container must reach an SSH agent with your Duke GitLab key.
# Duke VPN required: gitlab.dhe.duke.edu is only reachable on the Duke network.
# Rotating host key: on "REMOTE HOST IDENTIFICATION HAS CHANGED", run
#   ssh-keygen -R gitlab.dhe.duke.edu   then re-run this script.
#
# DEPLOYMENT ON PRCC (after this script runs)
# -------------------------------------------
#   git clone --branch main $BUNDLE_GITLAB_REMOTE pad_amp_ed_desc
#   cd pad_amp_ed_desc
#   # place the DHTS JDBC wrapper at ../drivers/prcc-jdbc-mssql-1.0-SNAPSHOT.jar
#   bash setup_prcc_env.sh
#   bash install_r_packages.sh      # first time only
#   conda activate openjdk
#   export KRB5CCNAME=FILE:~/krb5cc_java && kinit
#   bash run_analysis.sh
# =============================================================================

set -euo pipefail

# SSH agent fallback for docker exec sessions (devcontainer.json remoteEnv only
# applies to VS Code terminals, not bare docker exec).
if [[ -z "${SSH_AUTH_SOCK:-}" || ! -S "${SSH_AUTH_SOCK}" ]] && [[ -S /ssh-agent ]]; then
  export SSH_AUTH_SOCK=/ssh-agent
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---------------------------------------------------------------------------
# Load bundle config from .env files (workspace, then per-study override)
# ---------------------------------------------------------------------------
for ENV_FILE in "$REPO_ROOT/../.env" "$REPO_ROOT/.env"; do
  if [[ -f "$ENV_FILE" ]]; then
    while IFS= read -r line; do
      [[ "$line" =~ ^BUNDLE_|^INST_OMOP_|^CRAN_MIRROR= ]] && export "${line?}"
    done < "$ENV_FILE"
  fi
done

BUNDLE_GITLAB_REMOTE="${BUNDLE_GITLAB_REMOTE:-}"
BUNDLE_GIT_USER_NAME="${BUNDLE_GIT_USER_NAME:-}"
BUNDLE_GIT_USER_EMAIL="${BUNDLE_GIT_USER_EMAIL:-}"
BUNDLE_BRANCH="main"

# Bundle folder name — matches study_name in study_params.yaml (pad_amp_ed_desc)
# and the existing embedded git repo / GitLab remote. Kept underscore to avoid
# orphaning portable/pad_amp_ed_desc/.git.
STUDY_NAME="pad_amp_ed_desc"

# ---------------------------------------------------------------------------
# Validate config
# ---------------------------------------------------------------------------
if [[ -z "$BUNDLE_GITLAB_REMOTE" || "$BUNDLE_GITLAB_REMOTE" == *"CHANGE_ME"* ]]; then
  echo "[Bundle] ERROR: BUNDLE_GITLAB_REMOTE is not set or still contains CHANGE_ME."
  echo "         Set it in pad-amp-ed-desc/.env (or the workspace .env) to the full SSH URL."
  echo "         Example: git@gitlab.dhe.duke.edu:apj20/pad-amp-ed-desc.git"
  exit 1
fi

BUNDLE="$REPO_ROOT/portable/$STUDY_NAME"
DIST="$REPO_ROOT/dist"

if [[ ! -d "$BUNDLE" ]]; then
  echo "[Bundle] ERROR: portable bundle directory not found: $BUNDLE"
  exit 1
fi

mkdir -p "$DIST"

# ---------------------------------------------------------------------------
# Step 3 — Sync study content into the bundle
#   (a) Strategus inst/ (cohorts + spec JSON) + the spec builder
#   (b) report chain + retained custom step + covariate CSVs
# The PRCC runtime layer (config.R, run_analysis.R, R/connection.R, R/drivers.R,
# setup_prcc_env.sh, install_*, run_analysis.sh, export_results_for_review.R,
# vendor_packages/, drivers/prcc JDBC) is committed once and NOT touched here.
# ---------------------------------------------------------------------------
echo "[Step 3] Syncing Strategus inst/ and analysis specification ..."
# Full-directory sync equivalent to `rsync -a --delete` but without the rsync
# dependency (the dev container, where this script is run per the workspace
# convention, does not ship rsync). Rebuild inst/ from scratch each run so
# deletions in the source inst/ propagate.
rm -rf "$BUNDLE/inst"
mkdir -p "$BUNDLE/inst"
cp -a "$REPO_ROOT/inst/." "$BUNDLE/inst/"
cp -f "$REPO_ROOT/CreateStrategusAnalysisSpecification.R" \
      "$BUNDLE/CreateStrategusAnalysisSpecification.R"
if [[ ! -f "$BUNDLE/inst/padAmpEdDescAnalysisSpecification.json" ]]; then
  echo "  [WARN] inst/padAmpEdDescAnalysisSpecification.json not found."
  echo "         Run CreateStrategusAnalysisSpecification.R in the main repo first"
  echo "         so the transportable spec JSON exists before syncing."
fi
echo "  inst/ -> portable/$STUDY_NAME/inst/"
echo "  CreateStrategusAnalysisSpecification.R -> portable/$STUDY_NAME/"

echo "[Step 3] Syncing report chain + retained custom step + covariates ..."
copy_bundle_file() {
  local src="$REPO_ROOT/$1" dst="$BUNDLE/$2"
  if [[ ! -f "$src" ]]; then echo "  [WARN] Not found, skipping: $1"; return; fi
  mkdir -p "$(dirname "$dst")"
  cp -f "$src" "$dst"
  echo "  $1 -> portable/$STUDY_NAME/$2"
}
# report_extended.R is loaded as report.R on PRCC (see run_analysis.R). It
# sources report_helpers.R + report_descriptive.R (the prognostic/causal
# templates are guarded with file.exists() and deliberately NOT shipped).
copy_bundle_file "R/report_extended.R"     "R/report.R"
copy_bundle_file "R/report_helpers.R"      "R/report_helpers.R"
copy_bundle_file "R/report_descriptive.R"  "R/report_descriptive.R"
copy_bundle_file "scripts/analysis/descriptive_ed_analysis.R" \
                 "scripts/analysis/descriptive_ed_analysis.R"
if compgen -G "$REPO_ROOT/covariates/*.csv" > /dev/null 2>&1; then
  for _csv in "$REPO_ROOT/covariates/"*.csv; do
    [[ -f "$_csv" ]] && copy_bundle_file "covariates/$(basename "$_csv")" \
      "covariates/$(basename "$_csv")"
  done
else
  echo "  [WARN] No CSV files found in covariates/ — skipping."
fi

# ---------------------------------------------------------------------------
# Step 4 — Sync MSSQL JDBC JAR into bundle/drivers/ (fallback JDBC driver; the
# Kerberos wrapper JAR is placed by the site one level above the bundle)
# ---------------------------------------------------------------------------
echo "[Step 4] Syncing JDBC JAR ..."
JDBC_JAR=$(find "$REPO_ROOT/drivers/jdbc-runtime" -name "mssql-jdbc-*.jre11.jar" 2>/dev/null | head -1)
if [[ -z "$JDBC_JAR" ]]; then
  echo "  [WARN] JDBC JAR not found in drivers/jdbc-runtime/ — skipping."
else
  mkdir -p "$BUNDLE/drivers"
  cp -f "$JDBC_JAR" "$BUNDLE/drivers/"
  echo "  $(basename "$JDBC_JAR") -> portable/$STUDY_NAME/drivers/"
fi

# ---------------------------------------------------------------------------
# generate_bundle_env — writes .env with institution OMOP connection details
# from the workspace .env (INST_OMOP_*), for the Duke GitLab bundle only. The
# zip fallback ships generate_bundle_env_example's .env.example instead (see
# below) so no site-specific connection details leak into a bundle meant to
# be shared externally. Values single-quoted so backslashes in schema names
# (e.g. dhe\apj20) survive `source` with set -o allexport.
# ---------------------------------------------------------------------------
generate_bundle_env() {
  local dest="$1"
  local server database spn_host vocab_schema cdm_schema results_schema
  local cdm_id cdm_name cdm_desc header_note

  if [[ -z "${INST_OMOP_SERVER:-}" ]]; then
    echo "  [WARN] INST_OMOP_SERVER not set — .env will contain placeholders."
  fi
  server="${INST_OMOP_SERVER:-YOUR_SERVER.example.com}"
  database="${INST_OMOP_DATABASE:-YOUR_DATABASE}"
  spn_host="${INST_OMOP_SPN_HOST:-YOUR_SPN_HOST}"
  vocab_schema="${INST_OMOP_VOCAB_SCHEMA:-omop_vocab}"
  cdm_schema="${INST_OMOP_CDM_SCHEMA:-omop_cdm}"
  results_schema="${INST_OMOP_RESULTS_SCHEMA:-your_results_schema}"
  cdm_id="${INST_OMOP_CDM_DATABASE_ID:-your_cdm_v5.4}"
  cdm_name="${INST_OMOP_CDM_DATABASE_NAME:-Your Institution OMOP CDM}"
  cdm_desc="${INST_OMOP_CDM_DATABASE_DESCRIPTION:-Brief description of the patient population and database.}"
  header_note="All connection values are pre-populated by the study coordinator.\n# Only change OMOP_RESULTS_SCHEMA if you write to a different schema (domain\\\\netid)."

  {
    echo "# ============================================================================="
    echo "# .env — Site-specific OMOP connection for the pad-amp-ed-desc PRCC bundle."
    echo "# Generated by workflow/03_build_portable_analysis_bundle.sh."
    printf "# %b\n" "$header_note"
    echo "# ============================================================================="
    echo ""
    echo "# SQL Server connection"
  } > "$dest/.env"
  printf "OMOP_SERVER='%s'\n"                   "$server"         >> "$dest/.env"
  printf "OMOP_DATABASE='%s'\n"                 "$database"       >> "$dest/.env"
  printf "OMOP_SPN_HOST='%s'\n\n"               "$spn_host"       >> "$dest/.env"
  printf "# Schema names\n"                                       >> "$dest/.env"
  printf "OMOP_VOCAB_SCHEMA='%s'\n"             "$vocab_schema"   >> "$dest/.env"
  printf "OMOP_CDM_SCHEMA='%s'\n\n"             "$cdm_schema"     >> "$dest/.env"
  printf "# Personal write schema — pre-filled; change only if running as a different user\n" >> "$dest/.env"
  printf "OMOP_RESULTS_SCHEMA='%s'\n\n"         "$results_schema" >> "$dest/.env"
  printf "# Database metadata (written into output files)\n"      >> "$dest/.env"
  printf "OMOP_CDM_DATABASE_ID='%s'\n"          "$cdm_id"         >> "$dest/.env"
  printf "OMOP_CDM_DATABASE_NAME='%s'\n"        "$cdm_name"       >> "$dest/.env"
  printf "OMOP_CDM_DATABASE_DESCRIPTION='%s'\n" "$cdm_desc"       >> "$dest/.env"
  printf "\n# CRAN mirror — injected from workspace .env (CRAN_MIRROR)\n"       >> "$dest/.env"
  printf "CRAN_MIRROR='%s'\n" "${CRAN_MIRROR:-https://cloud.r-project.org}"     >> "$dest/.env"

  echo "  .env written with site-specific OMOP connection details"
}

# ---------------------------------------------------------------------------
# generate_bundle_env_example — writes .env.example for the zip fallback
# (dist/*.zip), meant for the VA or another institution rather than the Duke
# GitLab clone. Values are the literal sentinel "CHANGE_ME" -- matching what
# run_analysis.R's pre-flight validation and config.R's own unset= fallback
# both check for -- so the recipient must explicitly `cp .env.example .env`
# and fill in their own server/schema names by hand; there is no live .env
# in the zip at all (unlike the GitLab bundle, which ships Duke's real
# values pre-filled).
# ---------------------------------------------------------------------------
generate_bundle_env_example() {
  local dest="$1"
  {
    echo "# ============================================================================="
    echo "# .env.example — copy this to .env and fill in YOUR institution's OMOP"
    echo "# connection details by hand before running. This bundle is connection-"
    echo "# agnostic: it does not know your server, database, or schema names."
    echo "# Generated by workflow/03_build_portable_analysis_bundle.sh."
    echo "# ============================================================================="
    echo ""
    echo "# Authentication method -- see R/connection.R's header for full details."
    echo "#   sql       : SQL Server username + password (works almost everywhere;"
    echo "#               pick this first if you're not sure what your site uses)"
    echo "#   windows   : Windows Integrated Auth -- only works if R runs directly"
    echo "#               on a domain-joined Windows machine"
    echo "#   kerberos  : standard MSSQL JDBC JavaKerberos auth (Linux/Windows;"
    echo "#               requires a Kerberos ticket via kinit, no special JAR needed)"
    echo "#   kerberos_prcc : Duke PRCC's setup -- DO NOT use this outside Duke,"
    echo "#               it requires a Duke-proprietary JDBC wrapper JAR you won't have"
    echo "OMOP_AUTH_METHOD='sql'"
    echo ""
    echo "# SQL Server connection"
    echo "OMOP_SERVER='CHANGE_ME'          # e.g. sqlserver.yourinstitution.org"
    echo "OMOP_PORT='1433'                 # change only if your SQL Server uses a non-default port"
    echo "OMOP_DATABASE='CHANGE_ME'        # e.g. OMOP_CDM"
    echo "OMOP_USER='CHANGE_ME'            # required for OMOP_AUTH_METHOD=sql only"
    echo "OMOP_PASSWORD='CHANGE_ME'        # required for OMOP_AUTH_METHOD=sql only -- treat this file like a password, do not share/commit it"
    echo "OMOP_SPN_HOST='CHANGE_ME'        # only used by OMOP_AUTH_METHOD=kerberos/kerberos_prcc; optional for kerberos (see R/connection.R)"
    echo ""
    echo "# Schema names"
    echo "OMOP_VOCAB_SCHEMA='CHANGE_ME'    # e.g. omop_vocab"
    echo "OMOP_CDM_SCHEMA='CHANGE_ME'      # e.g. omop_cdm"
    echo ""
    echo "# Personal write schema -- where your own results/cohort tables get written"
    echo "OMOP_RESULTS_SCHEMA='CHANGE_ME'  # e.g. your_domain\\your_netid, or a schema you own"
    echo ""
    echo "# Database metadata (written into output files -- optional, but recommended"
    echo "# for the report's data-provenance table)"
    echo "OMOP_CDM_DATABASE_ID='CHANGE_ME'"
    echo "OMOP_CDM_DATABASE_NAME='CHANGE_ME'"
    echo "OMOP_CDM_DATABASE_DESCRIPTION='CHANGE_ME'"
    echo ""
    echo "# CRAN mirror -- the public default works everywhere; only change this"
    echo "# if your institution has its own mirror/proxy"
    echo "CRAN_MIRROR='https://cloud.r-project.org'"
  } > "$dest/.env.example"
  echo "  .env.example written (CHANGE_ME placeholders -- cp to .env and fill in by hand)"
}

# ---------------------------------------------------------------------------
# generate_bundle_readme — hybrid-pipeline README for pad-amp-ed-desc.
#   $1 dest, $2 generic ("true" writes the zip-fallback variant: no GitLab
#   clone step since the recipient already has the files from the zip, and
#   `cp .env.example .env` instead of "edit the pre-filled .env" since the
#   zip carries no institution-specific connection details at all).
# ---------------------------------------------------------------------------
generate_bundle_readme() {
  local dest="$1" generic="${2:-false}"
  local getting_started
  if [[ "$generic" == "true" ]]; then
    getting_started=$(cat << 'EOF'
```bash
# ── Unpack (once) ──
unzip pad_amp_ed_desc_*.zip -d pad_amp_ed_desc && cd pad_amp_ed_desc

# ── One-time setup ──
Rscript install_packages.R      # installs Strategus/HADES + report packages (from vendor_packages/ + CRAN)
cp .env.example .env            # then edit .env: fill in YOUR server, database, schema names, AND
                                 # OMOP_AUTH_METHOD (sql / windows / kerberos -- see .env.example and
                                 # R/connection.R's header for which one matches your site)

# ── Every session ──
bash run_analysis_generic.sh    # NOT run_analysis.sh -- that one is Duke-PRCC-specific (conda + Kerberos)
```

This is the connection-agnostic bundle (e.g. for the VA or another
institution) — it ships with `.env.example` only, not a pre-filled `.env`,
and supports 4 authentication methods (`sql`, `windows`, `kerberos`,
`kerberos_prcc`) so it can connect to SQL Server the way YOUR site actually
authenticates, not just Duke's Kerberos setup. `run_analysis.R` will refuse
to run with a clear error listing any field still left as `CHANGE_ME`.

If you don't know which auth method your site uses, ask your DBA/data team
how they connect to SQL Server today (a username+password login is `sql`,
the simplest and most broadly compatible option) — see `.env.example` and
the header comment in `R/connection.R` for a full decision guide.
EOF
)
  else
    getting_started=$(cat << EOF
\`\`\`bash
# ── Clone (once) ──
git clone ${BUNDLE_GITLAB_REMOTE} .

# ── One-time setup ──
bash setup_prcc_env.sh          # creates conda env, runs kinit
bash install_r_packages.sh      # installs Strategus/HADES + report packages (from vendor_packages/ + CRAN)
# Edit .env — confirm OMOP_RESULTS_SCHEMA is your domain\\netid write schema

# ── Every session ──
export KRB5CCNAME=FILE:~/krb5cc_java
kinit
conda activate openjdk
bash run_analysis.sh
\`\`\`
EOF
)
  fi
  local title="pad-amp-ed-desc — Duke PRCC Portable Analysis Bundle"
  local intro="Descriptive analysis of emergency-department utilization after major lower
extremity amputation, against the institutional OMOP CDM v5.4 SQL Server
database on Duke PRCC."
  local auth_line="Kerberos (institutional NetID) — no passwords stored in any file."
  local egress_line="This writes \`output/export_for_review/<timestamp>/\` with a small-cell-suppressed
archive of the Strategus outputs plus a reviewer manifest. It never moves
anything out of PRCC — clearing data-egress review and copying the artifact out
is done through official Duke channels. Confirm with Duke whether aggregate
CohortDiagnostics / CohortIncidence output and the Word report must clear review
before leaving the enclave."
  if [[ "$generic" == "true" ]]; then
    title="pad-amp-ed-desc — Portable Analysis Bundle (connection-agnostic)"
    intro="Descriptive analysis of emergency-department utilization after major lower
extremity amputation, against an institutional OMOP CDM v5.4 SQL Server
database. This bundle is connection-agnostic (e.g. for the VA or another
institution) — it does not assume Duke PRCC."
    auth_line="Kerberos (institutional NetID), if your site uses it — no passwords stored in any file."
    egress_line="This writes \`output/export_for_review/<timestamp>/\` with a small-cell-suppressed
archive of the Strategus outputs plus a reviewer manifest. It never moves
anything out of this environment on its own — clearing data-egress review and
copying the artifact out is done through YOUR institution's own review
process. Confirm with your institution whether aggregate CohortDiagnostics /
CohortIncidence output and the Word report must clear review before leaving
your analytic enclave."
  fi
  cat > "$dest/README.md" << EOF
# $title

$intro

**Generated:** $(date +%Y-%m-%d) by \`workflow/03_build_portable_analysis_bundle.sh\`

**Authentication:** $auth_line
**Java:** conda openjdk from miniforge — no system Java installation needed.
**JDBC driver:** pre-bundled in \`drivers/\` — no internet download needed.
**Analysis engine:** HYBRID — Strategus executes the transportable
\`inst/padAmpEdDescAnalysisSpecification.json\`, then a retained custom step and
Word-manuscript report run on top of the module outputs (see Pipeline below).

---

## Getting Started

$getting_started

---

## Pipeline (run_analysis.R)

1. **Strategus::execute()** — CohortGenerator + CohortDiagnostics +
   Characterization + CohortIncidence. Produces the cohort table, Table 2a
   incidence (CohortIncidence), and the standardized baseline characterization
   (Table S1b).
2. **run_vafi_plp()** — equal-weight VA-Frailty-Index discrimination/calibration
   via the PatientLevelPrediction package (Table 4, Fig 3) -> \`output/plp_vafi/\`.
3. **run_descriptive_ed_analysis()** — retained custom step: curated Table 1,
   Table 2b ED-visit diagnoses, VA-FI per-deficit odds ratios + forest plot, and
   CPT4/ICD-10-CM crosswalks -> \`output/descriptive/\`.
4. **generate_manuscript_report()** — reconfigures the module + custom outputs
   into \`output/pad-amp-ed-desc_report_<date>.docx\`.

Results are written under \`output/\` (gitignored). Kerberos tickets expire after
~10 hours; re-run \`kinit\` on authentication errors.

---

## Reproducibility

This analysis is **deterministic**: given the same CDM data snapshot and the same
OMOP vocabulary version, it reproduces exactly — run to run and site to site.
Verified by repeated clean runs producing byte-identical module outputs
(CohortIncidence incidence tables and the PatientLevelPrediction evaluation
statistics, including the AUROC confidence bounds).

- **No random number generation anywhere.** The VA-FI is applied as a fixed
  equal-weight existing model (no model fitting), there is no train/test split,
  and discrimination CIs use DeLong's analytic method (not bootstrap). No
  \`set.seed()\` is required.
- **Cohorts are generated fresh each run** (Strategus/CohortGenerator drops and
  recreates the cohort table), so a clean \`git clone\` → \`bash run_analysis.sh\`
  is fully reproducible. Do not hand-reuse a stale cohort table between runs.
- **The two inputs that govern results are the CDM data snapshot and the OMOP
  vocabulary version.** Concept sets expand through \`concept_ancestor\`, so a
  vocabulary update can change cohort membership. Both values are recorded in
  the report's Supplemental Table S1a (from \`cdm_source\`); pin/record them
  alongside any released result so the run can be reproduced.
- Cohort-definition SQL is standard OHDSI Circe output; the only tie-prone
  \`ORDER BY\` clauses order by event start date, and incidence is counted by
  date window, so tie-breaking cannot move a patient across a window boundary.

---

## Packaging results for data-egress review

\`run_analysis.sh\` only writes to \`output/\`. Preparing an egress candidate is a
separate manual step:

\`\`\`bash
Rscript export_results_for_review.R
\`\`\`

$egress_line
EOF
  echo "  README.md generated: $dest/README.md"
}

# ---------------------------------------------------------------------------
# Step 5 — Generate the bundle's README.md + .env
# ---------------------------------------------------------------------------
echo "[Step 5] Generating bundle README ..."
generate_bundle_readme "$BUNDLE"
echo "[Step 5] Generating bundle .env from INST_OMOP_* ..."
generate_bundle_env "$BUNDLE"

# ---------------------------------------------------------------------------
# Step 6 — Commit and push to GitLab (main branch)
# ---------------------------------------------------------------------------
echo "[Step 6] Pushing bundle to GitLab ($BUNDLE_GITLAB_REMOTE, branch: $BUNDLE_BRANCH) ..."
echo "  Checking SSH connectivity to GitLab ..."
if ! ssh -o BatchMode=yes -o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new \
        "$(echo "$BUNDLE_GITLAB_REMOTE" | sed 's|git@\([^:]*\):.*|\1|')" \
        2>&1 | grep -qiE 'welcome|authenticated|gitlab'; then
  echo "  [WARN] SSH connectivity check inconclusive — proceeding anyway."
  echo "         Ensure you are on the Duke VPN; verify with: ssh -T git@gitlab.dhe.duke.edu"
  echo "         On 'REMOTE HOST IDENTIFICATION HAS CHANGED': ssh-keygen -R gitlab.dhe.duke.edu"
fi

cd "$BUNDLE"

if [[ ! -d ".git" ]]; then
  echo "  Initialising git repo in portable/$STUDY_NAME/ ..."
  git init -b "$BUNDLE_BRANCH"
  git remote add origin "$BUNDLE_GITLAB_REMOTE"
else
  if git remote get-url origin &>/dev/null; then
    git remote set-url origin "$BUNDLE_GITLAB_REMOTE"
  else
    git remote add origin "$BUNDLE_GITLAB_REMOTE"
  fi
  if ! git rev-parse --verify "$BUNDLE_BRANCH" &>/dev/null; then
    git checkout -b "$BUNDLE_BRANCH"
  else
    git checkout "$BUNDLE_BRANCH"
  fi
fi

if [[ -n "$BUNDLE_GIT_USER_NAME" && "$BUNDLE_GIT_USER_NAME" != "CHANGE_ME" ]]; then
  git config user.name  "$BUNDLE_GIT_USER_NAME"
  git config user.email "$BUNDLE_GIT_USER_EMAIL"
fi

if ! grep -qx "output/" .gitignore 2>/dev/null; then
  echo "output/" >> .gitignore
fi

git add -A
COMMIT_MSG="chore: sync analysis bundle $(date -u +%Y-%m-%dT%H:%M:%SZ)"
if git diff --cached --quiet; then
  echo "  No changes to commit — bundle is already up to date."
else
  git commit -m "$COMMIT_MSG"
  echo "  Committed: $COMMIT_MSG"
fi

# GITLAB_PUSH_OK tracks push success so the summary + exit code at the end of
# this script are accurate. A push failure (e.g. no Duke VPN) must NOT abort
# the script under `set -e` -- the zip fallback below is specifically meant to
# cover exactly this case ("GitLab unreachable"), so skipping it here would
# defeat its purpose. || true on each attempt keeps `set -e` from firing;
# both attempts' exit codes still surface via GITLAB_PUSH_OK.
GITLAB_PUSH_OK=false
if git push --force-with-lease origin "$BUNDLE_BRANCH" 2>&1; then
  echo "  [OK] Pushed to $BUNDLE_GITLAB_REMOTE ($BUNDLE_BRANCH)"
  GITLAB_PUSH_OK=true
else
  echo "  Retrying with --set-upstream (first push to new remote) ..."
  if git push --set-upstream origin "$BUNDLE_BRANCH" 2>&1; then
    echo "  [OK] Pushed (with --set-upstream) to $BUNDLE_GITLAB_REMOTE ($BUNDLE_BRANCH)"
    GITLAB_PUSH_OK=true
  else
    echo "  [WARN] GitLab push failed (see error above -- commonly: not on the Duke VPN)."
    echo "         The commit above is saved locally in portable/$STUDY_NAME/.git;"
    echo "         re-run this script once connectivity is restored to push it."
  fi
fi

cd "$REPO_ROOT"

# ---------------------------------------------------------------------------
# Step 7 — Build a connection-agnostic dated zip fallback in dist/
# For the VA or another institution, not the Duke GitLab push: the zip ships
# .env.example (CHANGE_ME placeholders) instead of a live .env, and a README
# without the Duke-specific clone/Kerberos/data-egress assumptions. Both are
# generated fresh into the git-tracked $BUNDLE working tree just for the zip,
# then removed/restored afterward so the GitLab bundle (already committed and
# pushed in step 6) is unaffected.
# ---------------------------------------------------------------------------
echo "[Step 7] Building zip fallback (connection-agnostic) ..."
STAMP=$(date +"%Y%m%d")
BASE="${STUDY_NAME}_${STAMP}"
EXISTING_COUNT=$(find "$DIST" -name "${BASE}*.zip" 2>/dev/null | wc -l | tr -d ' ')
if [[ "$EXISTING_COUNT" -eq 0 ]]; then
  ZIP_NAME="${BASE}.zip"
else
  ZIP_NAME="${BASE}_${EXISTING_COUNT}.zip"
fi
ZIP_PATH="$DIST/$ZIP_NAME"

generate_bundle_readme "$BUNDLE" true
generate_bundle_env_example "$BUNDLE"
(
  cd "$BUNDLE"
  # .env is excluded entirely (not swapped to placeholders) so no
  # institution-specific connection details can leak into a bundle meant to
  # be shared externally -- the recipient must `cp .env.example .env`.
  find . -mindepth 1 ! -path "./output*" ! -path "./.git*" ! -name ".env" | sort | zip -q "$ZIP_PATH" -@
)
( cd "$BUNDLE" && git checkout -- README.md && rm -f .env.example )

SIZE_MB=$(du -sm "$ZIP_PATH" | cut -f1)
echo ""
if [[ "$GITLAB_PUSH_OK" == "true" ]]; then
  echo "[Step 6] GitLab push : OK -- $BUNDLE_GITLAB_REMOTE (branch: $BUNDLE_BRANCH)"
else
  echo "[Step 6] GitLab push : FAILED -- commit saved locally in portable/$STUDY_NAME/.git; re-run once connectivity is restored"
fi
echo "[Step 7] Zip fallback: $ZIP_PATH (${SIZE_MB} MB) — connection-agnostic, safe to share externally"
echo ""

if [[ "$GITLAB_PUSH_OK" == "true" ]]; then
  echo "Steps 1-7 complete."
  echo ""
  echo "To deploy on Duke PRCC:"
  echo "  git clone --branch $BUNDLE_BRANCH $BUNDLE_GITLAB_REMOTE $STUDY_NAME"
  echo "  cd $STUDY_NAME && git pull origin $BUNDLE_BRANCH   # to update an existing clone"
else
  echo "Steps 1-7 completed with warnings (step 6, GitLab push, failed -- see above)."
  echo "The step-7 zip fallback above is a usable substitute in the meantime."
  exit 1
fi
